name: nitella_app
description: "Nitella - Zero-Trust Proxy Mobile App"
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  grpc: ^5.1.0
  protobuf: ^6.0.0
  flutter_riverpod: ^2.4.9
  path_provider: ^2.1.2
  ffi: ^2.1.0
  synurang: ^0.2.0
  shared_preferences: ^2.5.4
  logger: ^2.0.0
  flutter_secure_storage: ^9.0.0
  local_auth: ^2.1.8
  share_plus: ^7.2.1
  yaml: ^3.1.2
  path: ^1.8.3
  firebase_messaging: ^14.7.10
  mobile_scanner: ^3.5.5
  cryptography: ^2.7.0
  qr_flutter: ^4.1.0
  device_info_plus: ^10.1.0
  fixnum: ^1.1.1
  convert: ^3.1.1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
